In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\bhn\Anaconda3\python.exe -m pip install --upgrade pip' command.


In [5]:
#Question 1 : 
#Write a Python program to print the NumPy version in your system.

import numpy as np
print(np.__version__)

1.18.1


In [19]:
#Question 2:
#Write a Python program to reverse an array (first element becomes last).

arr1 = np.array([2,4,6,1])
arr2_shape = arr1.shape
#print(arr1[-1:-(len(arr1)+1):-1])
j=len(arr1)-1
arr2=np.empty(arr2_shape,dtype=np.int32)
#print(arr2)
for i in np.arange(len(arr1)):
    arr2[i]=arr1[j]
    j-=1
print(arr2)

[1 6 4 2]


In [22]:
#Question 3:
#Write a Python program to convert a list and tuple into arrays.

l = [1,2,3,4]
tup = ("a","b","c")
list_arr = np.array(l)
tup_arr = np.array(tup)
print(list_arr , type(list_arr))
print(tup_arr , type(tup_arr))

[1 2 3 4] <class 'numpy.ndarray'>
['a' 'b' 'c'] <class 'numpy.ndarray'>


In [23]:
#Question 4:
#Write a Python program to find common values between two arrays.

arr1 = np.array([1,2,3,4])
arr2 = np.array([4,8,12,2])
for i in arr1:
    for j in arr2:
        if i == j:
            print(i)
            break

2
4


In [25]:
#Question 5:
#Write a Python program compare two arrays using numpy.

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,2,7,3])

print(arr1==arr2)
print(arr1>arr2)

[False  True False False]
[False False False  True]


In [37]:
#Question 6:
#Write a Python program to change the dimension of an array.

arr1 = np.array([1,2,3])
arr2 = np.array([5,6,7])

res_arr = np.stack((arr1,arr2),axis=0)
print(res_arr.ndim)

2


In [67]:
#Question 7:
#Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100.

arr = np.arange(1,101).reshape(10,10)
#print(arr)
#print(arr)
bool_arr1 = (arr%3==0)
#print(bool_arr1)
for i in np.arange(len(bool_arr1)):
    for j in np.arange(len(bool_arr1[i])):
        if bool_arr1[i][j]==False:
            if arr[i][j]%5==0:
                bool_arr1[i][j]=True
res_arr = arr[bool_arr1]
print(np.sum(res_arr))
    #print(arr%5==0)

2418


In [68]:
#Question 8:
#Write a Python program to convert a NumPy array into Python list structure.

arr1 = np.array([1,2,3,4,5])
new_list = list(arr1)
print(new_list,type(new_list))

[1, 2, 3, 4, 5] <class 'list'>


In [69]:
#Question 9:
#Write a Python program to how to add an extra column to a numpy array

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[6,7,8],[9,10,11]])
arr3=np.concatenate((arr1,arr2),axis=1)
print(arr3)

[[ 1  2  3  6  7  8]
 [ 4  5  6  9 10 11]]


In [73]:
#Question 10:
#Write a Python program to check whether the numpy array is empty or not.
arr = np.array([])
if np.size(arr)==0:
    print("Array Is An Empty Array")
else:
    print("Array Is Not An Empty Array")


Array Is An Empty Array


In [75]:
#Question 11:
#Write a Python program to normalize a 3x3 random matrix.
x= np.random.randn(3,3)
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[ 0.6069499   0.36223933 -0.09243648]
 [-0.98286517  0.53198278  0.7286565 ]
 [ 0.01752133 -0.13457474 -0.91091061]]
After normalization:
[[0.92888983 0.78591146 0.52025557]
 [0.         0.88508838 1.        ]
 [0.58450122 0.49563523 0.04204128]]


In [76]:
#Question 12:
#How to ignore all numpy warnings (not recommended)?
np.seterr(all="ignore")


{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [78]:
#Question 13:
# How to swap two rows of an array?

arr = np.array([[1,2,3],[4,5,6]])
arr2=np.empty(arr.shape,dtype=np.int32)
j=len(arr)-1
for i in np.arange(len(arr)):
    arr2[i]=arr[j]
    j-=1
print(arr2)

[[4 5 6]
 [1 2 3]]


In [88]:
#Question 14:
#Python program to create a random vector of size 10 and sort it.

arr = np.random.randn(10,)
res_arr=np.array(arr,dtype=np.int32)
sort_arr=np.sort(res_arr)
print(sort_arr)

[-2 -1 -1 -1  0  0  0  0  0  1]


In [102]:
#Question 15:
#Write a Python program to check two random arrays are equal or not.

arr1 = np.empty((5,),dtype=np.int32)
#arr1 = np.array([6,2,1,5])
arr2 = np.empty((5,),dtype=np.int32)
print(arr1)
print(arr2)
arr3=np.sort(arr1)
arr4=np.sort(arr2)
res_arr = (arr3==arr4)
if False in res_arr:
    print("Two arrays are not equal")
else:
    print("Two arrays are  equal")
#print(arr2)

[3 4 5 6 7]
[3 4 5 6 7]
Two arrays are  equal


In [103]:
#Question 16
#Write a Python program to add, subtract, multiply, divide arguments element-wise.

arr1 = np.array([1,2,3,4])
arr2 = np.array([6,7,8,9])
print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))

[ 7  9 11 13]
[-5 -5 -5 -5]
[ 6 14 24 36]
[0.16666667 0.28571429 0.375      0.44444444]


In [104]:
#Question 17
#Write a Python program to get the dates of yesterday, today and tomorrow.

today = np.datetime64('today', 'D')
print("Today: ", today)
  
# for yesterday
yesterday = np.datetime64('today', 'D')- np.timedelta64(1, 'D')
  
print("Yesterday: ", yesterday)
  
# for tomorrow
tomorrow = np.datetime64('today', 'D')+ np.timedelta64(1, 'D')
  
print("Tomorrow: ", tomorrow)


Today:  2022-05-14
Yesterday:  2022-05-13
Tomorrow:  2022-05-15
